initial bootstrap creation
wolox-training/serenity-selenium-bootstrap pull request #2
Opened 2022-01-11 17:28 UTC by WenSierra

initial bootstrap creation for screenplay and serenity

2022-01-11 18:20 UTC, gabrielbori requested changes

2022-01-11 18:20 UTC, gabrielbori commented on build.gradle
> +
leave just one empty line

2022-01-11 18:20 UTC, gabrielbori commented on build.gradle
> +
same

2022-01-11 18:20 UTC, gabrielbori commented on gradlew.bat
> +
same

2022-01-11 18:20 UTC, gabrielbori commented on src/main/java/com/wolox/certification/demoblaze/questions/GetTheWelcome.java
> +
same

2022-01-11 18:20 UTC, gabrielbori commented on src/main/java/com/wolox/certification/demoblaze/userinterface/DemoBlazePageHome.java
> +package com.wolox.certification.demoblaze.userinterface;
check if it should be "userInterface".

2022-01-11 18:20 UTC, gabrielbori commented on src/main/java/com/wolox/certification/demoblaze/userinterface/LoginPage.java
> +
leave just one empty line

2022-01-11 18:20 UTC, gabrielbori commented on src/main/java/com/wolox/certification/demoblaze/userinterface/LoginPage.java
> +    public static final Target WELCOME_MESSAGE = Target.the("mensaje de bienvenida").located(By.id("nameofuser"));
The whole code is in english. There is no point in having this in spanish

2022-01-13 16:43 UTC, WenSierra commented on src/main/java/com/wolox/certification/demoblaze/userinterface/DemoBlazePageHome.java
> +package com.wolox.certification.demoblaze.userinterface;
yes it should be

2022-01-17 18:03 UTC, milowolox commented on src/test/java/com/wolox/certification/demoblaze/stepsdefinitions/LoginStepsDefinitions.java
> +                        .orComplainWith(TheTextIsNotOnScreen.class,"El mensaje de bienvenida no esta en la pantalla"));
Garantizar que el mensaje sea parametrizable desde la excepción.

2022-01-17 18:03 UTC, milowolox commented on src/main/java/com/wolox/certification/demoblaze/userinterfaces/DemoBlazePageHome.java
> +@DefaultUrl("https://www.demoblaze.com")
Garantizar que la URL sea un parámetro de la automatización para que luego está sea enviada a través del CI. Adicionalmente aprovecha los métodos que trae screenplay para no tener que implementar objetos de POM.

2022-01-18 21:19 UTC, milowolox approved these changes

2022-01-18 21:51 UTC, merged